### ISSUE TITLE
Any Contributions for Hacktoberfest is welcome

### ISSUE THREAD

**Issue by SURYAKANTSHARMA** [SURYAKANTSHARMA/UberCarAnimation#3]
Any Contributions for Hacktoberfest is welcome 🥇 
Ideas
- travis CI is failing can fix that 
- Any new feature/Idea
- test cases

**Comment by zappycode** [comment]
Hi! I'd like to do this as part of Hacktober. Do I need to be assigned?

**Comment by SURYAKANTSHARMA** [comment]
You can pick any of above mentioned . You raise a valuable PR nothing 👍

**Comment by zappycode** [comment]
Cool!
